(function() {var implementors = {};
implementors['dbus'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.BusType.html' title='dbus::BusType'>DBusBusType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.NameFlag.html' title='dbus::NameFlag'>DBusNameFlag</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.RequestNameReply.html' title='dbus::RequestNameReply'>DBusRequestNameReply</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.ReleaseNameReply.html' title='dbus::ReleaseNameReply'>DBusReleaseNameReply</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.MessageType.html' title='dbus::MessageType'>DBusMessageType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.WatchEvent.html' title='dbus::WatchEvent'>DBusWatchEvent</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/enum.ArrayError.html' title='dbus::ArrayError'>ArrayError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='dbus/struct.Watch.html' title='dbus::Watch'>Watch</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/tree/enum.EmitsChangedSignal.html' title='dbus::tree::EmitsChangedSignal'>EmitsChangedSignal</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='dbus/tree/enum.Access.html' title='dbus::tree::Access'>Access</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
