(function() {var implementors = {};
implementors['dbus'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.BusType.html' title='dbus::BusType'>DBusBusType</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.NameFlag.html' title='dbus::NameFlag'>DBusNameFlag</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.RequestNameReply.html' title='dbus::RequestNameReply'>DBusRequestNameReply</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.ReleaseNameReply.html' title='dbus::ReleaseNameReply'>DBusReleaseNameReply</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.MessageType.html' title='dbus::MessageType'>DBusMessageType</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.ArrayError.html' title='dbus::ArrayError'>ArrayError</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='dbus/struct.OwnedFd.html' title='dbus::OwnedFd'>OwnedFd</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.MessageItem.html' title='dbus::MessageItem'>MessageItem</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='dbus/struct.Message.html' title='dbus::Message'>Message</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='dbus/struct.Error.html' title='dbus::Error'>Error</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='dbus/enum.ConnectionItem.html' title='dbus::ConnectionItem'>ConnectionItem</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='dbus/struct.Connection.html' title='dbus::Connection'>Connection</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
